services:
  mysql:
    image: mysql:8.0
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: financas
      MYSQL_USER: financas_user
      MYSQL_PASSWORD: financas_pass
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - financas_net

volumes:
  db_data:

networks:
  financas_net:
    driver: bridge
